import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, Clock3, Compass, Instagram, MapPin, Menu, Play, Quote, Send, X } from 'lucide-react';
import { destinations, gallery, packages, photos } from './data';
import { submitEnquiry } from './lib/supabase';

const logo = '/my-tripon-wordmark.png';
const links = [['About','/about'],['Destinations','/destinations'],['Tour packages','/packages'],['Experiences','/#experiences'],['Gallery','/gallery'],['Stories','/testimonials'],['Honours','/awards']];

function Header(){
 const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(window.scrollY>20);
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>20);window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
 return <><a className="skip-link" href="#main-content">Skip to content</a><div className="utility"><span>Thoughtfully planned journeys, made personal</span><span className="utility-right">India & beyond <i/> <a href="tel:+917034991100">Talk to our team&nbsp; ↗</a></span></div><header className={`header ${scrolled?'scrolled':''}`}><Link to="/" aria-label="My Tripon Travel home" className="brand"><img src={logo} alt="My Tripon Travel — Explore, Experience, Enjoy"/></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'} aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav className={open?'nav open':'nav'} aria-label="Main navigation">{links.map(([label,path])=><NavLink onClick={()=>setOpen(false)} key={path} to={path}>{label}</NavLink>)}<Link className="nav-cta" onClick={()=>setOpen(false)} to="/contact">Plan my trip <ArrowUpRight size={15}/></Link></nav></header></>;
}

function Footer(){return <footer className="footer"><div className="footer-top"><div className="footer-brand"><img src={logo} alt="My Tripon Travel"/><p>Explore <b>•</b> Experience <b>•</b> Enjoy</p><span>Good journeys begin with a good conversation.</span></div><div><h4>Find your way</h4><Link to="/packages">Tour packages</Link><Link to="/destinations">Destinations</Link><Link to="/gallery">Traveller gallery</Link><Link to="/testimonials">Traveller stories</Link></div><div><h4>The company</h4><Link to="/about">About us</Link><Link to="/awards">Awards & honours</Link><Link to="/contact">Contact</Link><a href="https://mytripontravel.com">mytripontravel.com</a></div><div><h4>Come say hello</h4><a href="tel:+917034991100">+91 70349 91100</a><a href="tel:+918089001122">+91 80890 01122</a><a href="tel:+917592999111">+91 75929 99111</a><a href="mailto:infomytripontravel@gmail.com">infomytripontravel@gmail.com</a><span>K Block, Mahipalpur,<br/>Delhi – 110037</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} My Tripon Travel</span><span>Made for the places that stay with you.</span><span>Managing Director&nbsp; · &nbsp;Shaji. CG</span></div></footer>}

function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><span/>{children}</div>}
function SectionTitle({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="section-title"><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}

function EnquiryForm({compact=false}:{compact?:boolean}){
 const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle'); const [message,setMessage]=useState('');
 async function handle(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);if(data.get('website'))return;const vals=Object.fromEntries([...data.entries()].map(([k,v])=>[k,String(v)]));setStatus('loading');try{const result=await submitEnquiry(vals);setMessage(result.demo?'Thanks — your enquiry is ready. Connect the site to Supabase to receive it in your inbox.':'Thank you. Our team will be in touch soon.');setStatus('success');form.reset()}catch{setMessage('Something went wrong. Please call us and we’ll be glad to help.');setStatus('error')}}
 return <form className={`enquiry-form ${compact?'compact':''}`} onSubmit={handle}>
  <label>Your name<input name="name" autoComplete="name" required placeholder="How should we address you?" minLength={2}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required placeholder="+91" pattern="[+0-9()\-\s]{8,}" title="Enter a valid phone number"/></label>
  {!compact&&<><label>Email address <span className="optional">Optional</span><input name="email" type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Where to? <select name="destination" defaultValue=""><option value="">Choose a destination</option>{['Kerala','Kashmir','Rajasthan','Goa','Dubai','Thailand','Bali','Maldives','Europe','Somewhere else'].map(x=><option key={x}>{x}</option>)}</select></label><label>When would you like to travel?<select name="month" defaultValue=""><option value="">Select a month</option>{['January','February','March','April','May','June','July','August','September','October','November','December','Dates are flexible'].map(x=><option key={x}>{x}</option>)}</select></label><label>Travellers<input type="number" name="travellers" min="1" max="40" placeholder="2"/></label><label className="full">A little about the trip <span className="optional">Optional</span><textarea name="message" rows={3} placeholder="The places, pace or moments you have in mind…"/></label></>}
  <input className="honeypot" tabIndex={-1} autoComplete="off" name="website" aria-hidden="true"/><button className="button gold" disabled={status==='loading'}>{status==='loading'?'Sending…':status==='success'?<>Sent <Check size={16}/></>:<>Plan my trip <ArrowRight size={16}/></>}</button>{status!=='idle'&&<div role="status" className={`form-message ${status}`}>{message}</div>}
 </form>
}

function Home(){const navigate=useNavigate();const [trip,setTrip]=useState('');return <>
 <section className="hero"><img className="hero-image" src={photos.hero} fetchPriority="high" alt="A tropical Indian Ocean shoreline at first light"/><div className="hero-shade"/><div className="hero-content"><Eyebrow>MY TRIPON TRAVEL&nbsp; · &nbsp;INDIA & BEYOND</Eyebrow><h1>Somewhere<br/><em>good</em> is waiting.</h1><p>Thoughtful holidays, shaped around the way you want to see the world.</p><div className="hero-actions"><Link to="/packages" className="button gold">Explore our journeys <ArrowRight size={17}/></Link><Link to="/contact" className="text-link light">Let’s plan yours <ArrowUpRight size={16}/></Link></div></div><div className="hero-aside"><span>01 / 04</span><i/><span>A different kind of getaway</span></div><a href="#intro" className="scroll-cue" aria-label="Scroll to discover"><ArrowDown size={16}/><span>SCROLL TO DISCOVER</span></a><div className="hero-caption">MUNNAR, KERALA <span>10°05′N&nbsp; 77°03′E</span></div>
 <div className="finder"><div className="finder-label"><Compass size={18}/><span>Find your kind of away</span></div><label><span>Destination</span><select value={trip} onChange={e=>setTrip(e.target.value)}><option value="">Anywhere you like</option>{destinations.map(d=><option key={d.name}>{d.name}</option>)}</select></label><label><span>Travel style</span><select><option>Choose your pace</option><option>Family holiday</option><option>Slow & scenic</option><option>Adventure</option><option>Honeymoon</option></select></label><Link to={trip?`/destinations/${trip.toLowerCase()}`:'/packages'} className="button teal">Find my trip <ArrowRight size={16}/></Link></div>
 </section>
 <section className="intro section-pad" id="intro"><div className="intro-mark"><div className="mark-crop"><img src="/tripon-mark.png" alt=""/></div><span>EXPLORE · EXPERIENCE · ENJOY</span></div><div className="intro-copy"><Eyebrow>A BETTER WAY TO GET THERE</Eyebrow><h2>Every good trip<br/>starts <em>with a feeling.</em></h2><p>Maybe it’s the promise of cool air in the hills. A new city on foot. Or a few unhurried days by the water. Tell us what you’re looking for; we’ll help you find your way there.</p><Link to="/about" className="text-link">Get to know us <ArrowRight size={16}/></Link></div><span className="intro-note">Explore<br/>Experience<br/>Enjoy<span className="gold-dot">.</span></span></section>
 <section className="destinations section-pad"><div className="title-row"><SectionTitle eyebrow="A PLACE TO BEGIN" title="Where to next?" copy="A few places we keep coming back to — each with its own way of making time slow down."/><Link to="/destinations" className="text-link desktop-link">All destinations <ArrowRight size={16}/></Link></div><div className="destination-grid"><Link className="destination-feature" to="/destinations/kerala"><img src={photos.kerala} alt="Houseboat on the Kerala backwaters" loading="lazy"/><span className="tile-index">01 / SOUTH INDIA</span><div className="destination-caption"><div><small>BACKWATERS · HIGHLANDS</small><h3>Kerala</h3></div><span className="circle-arrow"><ArrowUpRight/></span></div></Link><Link className="destination-tile dest-kashmir" to="/destinations/kashmir"><img src={photos.kashmir} alt="Mountain landscape in Kashmir" loading="lazy"/><div className="destination-caption"><div><small>THE HIMALAYAS</small><h3>Kashmir</h3></div><span className="circle-arrow"><ArrowUpRight/></span></div></Link><Link className="destination-tile dest-rajasthan" to="/destinations/rajasthan"><img src={photos.rajasthan} alt="Historic architecture in Rajasthan" loading="lazy"/><div className="destination-caption"><div><small>HERITAGE · DESERT</small><h3>Rajasthan</h3></div><span className="circle-arrow"><ArrowUpRight/></span></div></Link><Link className="destination-tile dest-bali" to="/destinations/bali"><img src={photos.bali} alt="Green temple landscapes in Bali" loading="lazy"/><div className="destination-caption"><div><small>ISLAND TIME · INDONESIA</small><h3>Bali</h3></div><span className="circle-arrow"><ArrowUpRight/></span></div></Link></div><Link to="/destinations" className="text-link mobile-link">Explore all destinations <ArrowRight size={16}/></Link></section>
 <section className="packages section-pad"><div className="title-row"><SectionTitle eyebrow="MADE TO MEAN SOMETHING" title="Journeys with a little more in them." copy="Considered routes, breathing room, and the details that make a trip feel like yours."/><Link to="/packages" className="text-link desktop-link">See all journeys <ArrowRight size={16}/></Link></div><div className="package-list">{packages.slice(0,3).map((p,i)=><Link className="package-row" to={`/packages/${p.slug}`} key={p.slug}><span className="package-no">0{i+1}</span><img src={p.image} alt="" loading="lazy"/><div className="package-info"><span>{p.place} <i/> {p.style}</span><h3>{p.title}</h3><p>{p.desc}</p></div><div className="package-meta"><span><Clock3 size={15}/>{p.duration}</span><span className="text-link">View the journey <ArrowUpRight size={16}/></span></div></Link>)}</div></section>
 <section className="experience section-pad" id="experiences"><div className="experience-image"><img src={photos.beach} alt="Soft evening light over a quiet beach" loading="lazy"/><div className="experience-stamp">YOUR<br/>OWN<br/><em>PACE</em></div></div><div className="experience-content"><Eyebrow>THE WAY YOU LIKE TO TRAVEL</Eyebrow><h2>Travel<br/><em>your way.</em></h2><p>Some trips are about doing it all. Others are about doing very little, very well. Start with what matters to you.</p><div className="experience-links">{['Family holidays','Honeymoon & couples','Heritage & culture','Beach escapes','Hills & adventure','International trips'].map((x,i)=><Link to="/contact" key={x}><span>0{i+1}</span>{x}<ArrowUpRight size={16}/></Link>)}</div></div></section>
 <section className="itinerary section-pad"><div className="itinerary-copy"><Eyebrow>A JOURNEY, AT A GLANCE</Eyebrow><span className="days">07 <small>DAYS</small></span><h2>The Kerala<br/><em>slow-down.</em></h2><p>From a harbour town that wakes early to tea hills that disappear into mist. A week to see the best of Kerala without rushing through it.</p><Link className="button cream" to="/packages/kerala-backwaters">See the itinerary <ArrowRight size={16}/></Link><span className="route-label">KOCHI — MUNNAR — THEKKADY — ALLEPPEY</span></div><div className="route-map"><div className="route-photo"><img src={photos.kerala} alt="Kerala hillside and backwaters" loading="lazy"/></div><div className="route-line"><div><span>01</span><b>Kochi</b><small>Arrive · wander the old quarter</small></div><div><span>03</span><b>Munnar</b><small>Tea roads · mountain air</small></div><div><span>05</span><b>Thekkady</b><small>Spice country · forest trails</small></div><div><span>07</span><b>Alleppey</b><small>Backwaters · a slower finish</small></div></div><span className="route-pin"><MapPin size={18}/></span></div></section>
 <section className="why section-pad"><div><Eyebrow>THE MY TRIPON APPROACH</Eyebrow><h2>It should feel like<br/><em>your kind of trip.</em></h2><p>Good planning leaves room for the unexpected. We start by listening, then bring the pieces together with care.</p><Link to="/about" className="text-link">A little about us <ArrowRight size={16}/></Link></div><div className="principles">{[['01','A plan that listens','We begin with your people, your pace and the moments you want to make room for.'],['02','Thoughtful, not overfilled','A considered itinerary gives each place the time it deserves — and you the space to enjoy it.'],['03','Here when you need us','From the first conversation to the journey itself, a real person is within reach.']].map(([n,t,d])=><div key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={18}/></div>)}</div></section>
 <section className="gallery-section section-pad"><div className="title-row"><SectionTitle eyebrow="TAKEN ALONG THE WAY" title="Real journeys. Real moments." copy="A glimpse of the places and memories travellers bring home."/><Link to="/gallery" className="text-link desktop-link">Visit the gallery <ArrowRight size={16}/></Link></div><div className="gallery-grid"><Link to="/gallery" className="gallery-img g1"><img src={photos.family} alt="Traveller looking out over a mountain valley" loading="lazy"/><span>THE LONG WAY ROUND</span></Link><Link to="/gallery" className="gallery-img g2"><img src={photos.taj} alt="Taj Mahal in morning light" loading="lazy"/></Link><Link to="/gallery" className="gallery-img g3"><img src={photos.coast} alt="A quiet coastal afternoon" loading="lazy"/><span>SALT IN THE AIR</span></Link><Link to="/gallery" className="gallery-video"><img src={photos.bali} alt="Bali travel story video preview" loading="lazy"/><span className="play"><Play fill="currentColor" size={18}/></span><small>TRAVELLER FILM · BALI</small></Link><Link to="/gallery" className="gallery-img g4"><img src={photos.mountains} alt="A mountain road disappearing into the clouds" loading="lazy"/></Link></div><Link to="/gallery" className="text-link mobile-link">See the full gallery <ArrowRight size={16}/></Link></section>
 <section className="story-section"><div className="story-image"><img src={photos.family} alt="A family looking out over a scenic valley" loading="lazy"/><span className="story-play"><Play fill="currentColor"/></span><small>VIDEO STORY · DEMO PREVIEW</small></div><div className="story-copy"><Eyebrow>NOTES FROM THE ROAD</Eyebrow><Quote size={28} className="quote-icon"/><blockquote>“The best part was having enough time to simply sit, look around and take it all in.”</blockquote><div className="story-credit"><span className="avatar">T</span><div><b>Traveller story</b><small>Illustrative demo content</small></div></div><Link to="/testimonials" className="text-link">More stories from the road <ArrowRight size={16}/></Link><p className="demo-note">Video and testimonial previews shown for demonstration. Traveller submissions can be added here.</p></div></section>
 <section className="honours section-pad"><div className="honours-mark">M<span>T</span></div><div><Eyebrow>RECOGNITION, WHEN IT COMES</Eyebrow><h2>Good work speaks<br/><em>for itself.</em></h2><p>This space is being kept for the awards, honours and milestones My Tripon Travel earns. It will be updated with verified recognition.</p><Link to="/awards" className="text-link">Awards & honours <ArrowRight size={16}/></Link></div><div className="honours-note"><span>01 / OUR STORY</span><div className="fine-rule"/><span>Verified milestones,<br/>shared with care.</span></div></section>
 <section className="journal section-pad"><div className="title-row"><SectionTitle eyebrow="FIELD NOTES" title="A little inspiration for the road."/><Link to="/destinations" className="text-link desktop-link">Explore places <ArrowRight size={16}/></Link></div><div className="journal-grid">{[{title:'When Kashmir turns the colour of autumn',cat:'SEASONAL NOTES · 5 MIN READ',image:photos.kashmir},{title:'A first-timer’s guide to slowing down in Bali',cat:'ISLAND JOURNAL · 6 MIN READ',image:photos.bali},{title:'Taking the scenic route through Rajasthan',cat:'CULTURE & PLACE · 4 MIN READ',image:photos.rajasthan}].map((j,i)=><Link to="/destinations" className="journal-card" key={j.title}><div><img src={j.image} alt="" loading="lazy"/></div><small>{j.cat}</small><h3>{j.title}</h3><span>Read the note <ArrowUpRight size={15}/></span></Link>)}</div></section>
 <section className="lead section-pad" id="plan"><div className="lead-copy"><Eyebrow>A GOOD PLACE TO START</Eyebrow><h2>Tell us where<br/>you want to go.<br/><em>We’ll take it from there.</em></h2><p>A few details are all we need to begin. Or just call and tell us the story.</p><a className="lead-phone" href="tel:+917034991100">+91 70349 91100 <ArrowUpRight size={17}/></a></div><div className="lead-form"><div className="form-heading"><span>01 — 02 MIN</span><p>Tell us a little about your plans.</p></div><EnquiryForm/></div></section>
 
 </>}

function PageHero({label,title,copy,image}:{label:string;title:ReactNode;copy:string;image:string}){return <section className="page-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(13,46,57,.75),rgba(13,46,57,.1)),url(${image})`}}><div><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{copy}</p></div></section>}
function About(){return <><PageHero label="A LITTLE ABOUT US" title={<>Good journeys<br/><em>begin with listening.</em></>} copy="We’re My Tripon Travel — a travel company built around the idea that the best trips feel personal from the very first conversation." image={photos.coast}/><section className="about-body section-pad"><div><Eyebrow>EXPLORE · EXPERIENCE · ENJOY</Eyebrow><h2>A thoughtful travel partner for wherever life takes you.</h2></div><div><p>From family holidays close to home to long-awaited journeys further afield, My Tripon Travel helps bring the details together. We believe a good itinerary has a point of view, a comfortable pace and room to make the day your own.</p><p>Our work starts with a conversation. What do you want to see? Who’s coming along? What does a good holiday feel like to you? Those answers shape the route, the rhythm and the little details along the way.</p><p>Based in Mahipalpur, Delhi, we plan journeys across India and international destinations.</p><Link to="/contact" className="button teal">Start a conversation <ArrowRight size={16}/></Link></div></section><div className="about-image"><img src={photos.kerala} alt="Aerial view over Kerala's green landscape" loading="lazy"/><span>TRAVEL, AT YOUR PACE.</span></div><section className="about-body section-pad"><div><Eyebrow>THE PEOPLE BEHIND THE PLANS</Eyebrow><h2>Every itinerary has a person on the other end.</h2></div><div><p>Shaji. CG, Managing Director, and the My Tripon Travel team are here to help shape a journey that feels right for you.</p><a href="mailto:infomytripontravel@gmail.com" className="text-link">Write to our team <ArrowRight size={16}/></a></div></section></>}

function Packages(){return <><PageHero label="TAKE THE SCENIC ROUTE" title={<>Journeys worth<br/><em>making time for.</em></>} copy="Considered starting points for your next holiday. Every itinerary can be shaped around you." image={photos.rajasthan}/><section className="package-catalog section-pad"><SectionTitle eyebrow="A FEW WAYS TO BEGIN" title="Find a journey that feels like yours." copy="These sample journeys are a starting point. Tell us what you have in mind and we’ll make a plan together."/><div className="catalog-grid">{packages.map((p,i)=><Link className="catalog-card" to={`/packages/${p.slug}`} key={p.slug}><div className="catalog-image"><img src={p.image} alt={p.place} loading="lazy"/><span>0{i+1} / JOURNEY</span><i><ArrowUpRight/></i></div><div className="catalog-copy"><small>{p.place} · {p.duration}</small><h3>{p.title}</h3><p>{p.desc}</p><span className="text-link">Explore this journey <ArrowRight size={15}/></span></div></Link>)}</div></section><section className="catalog-cta"><div><Eyebrow>NOT QUITE WHAT YOU HAD IN MIND?</Eyebrow><h2>Let’s make a journey<br/><em>around you.</em></h2></div><Link to="/contact" className="button gold">Talk to a trip planner <ArrowRight size={16}/></Link></section></>}

function PackageDetail(){const {slug=''}=useParams();const p=packages.find(x=>x.slug===slug)||packages[0];return <><PageHero label={`${p.place.toUpperCase()} · ${p.duration.toUpperCase()}`} title={<>{p.title}<br/><em>at your own pace.</em></>} copy={p.desc} image={p.image}/><div className="detail-layout section-pad"><main><Eyebrow>THE IDEA</Eyebrow><h2>A little structure.<br/><em>Plenty of room.</em></h2><p className="detail-intro">A thoughtfully paced journey through {p.place}, with memorable stops, time to settle in and the freedom to make each day your own. The route can be adjusted to suit your dates, interests and travelling party.</p><div className="detail-highlights"><span>THE FEELING</span><b>{p.style}</b><span>THE PACE</span><b>{p.duration}</b><span>THE STARTING POINT</span><b>{p.place}</b></div><h2 className="itinerary-heading">A first look at the route</h2><div className="day-list">{[['01','Arrive & find your bearings','A relaxed arrival and time to settle in. We’ll help make the first evening easy.'],['02','Get to know the place','A guided introduction, with a little time left free to follow your curiosity.'],['03','Take the scenic road','A change of pace and scenery, with stops worth making along the way.'],['04','A day that’s yours','Keep the day open, or ask us to arrange an experience around what you enjoy.'],['05','One last morning','A gentle finish, with the details of your onward journey taken care of.']].map(d=><div className="day" key={d[0]}><span>{d[0]}</span><div><h3>{d[1]}</h3><p>{d[2]}</p></div><ChevronDown size={16}/></div>)}</div><div className="include-columns"><div><h3>We can arrange</h3><ul><li>Accommodation to suit your style</li><li>Private transfers and local transport</li><li>Guided experiences and local introductions</li><li>Thoughtful pacing between each stop</li></ul></div><div><h3>Planned around you</h3><ul><li>Dates and trip length</li><li>Room and transport preferences</li><li>Dietary and accessibility needs</li><li>Experiences that matter to you</li></ul></div></div><p className="demo-note">Illustrative itinerary for demonstration; final inclusions and route are confirmed with your trip planner.</p></main><aside className="detail-aside"><span>YOUR JOURNEY, YOUR WAY</span><h3>Let’s shape the details together.</h3><p>Share your dates and what you’re looking for. We’ll get back to you with a considered next step.</p><Link to="/contact" className="button gold">Enquire about this trip <ArrowRight size={16}/></Link><a href="tel:+917034991100" className="text-link">Or call +91 70349 91100</a></aside></div><div className="related section-pad"><SectionTitle eyebrow="MORE PLACES TO GO" title="Keep looking around."/><div className="catalog-grid">{packages.filter(x=>x.slug!==slug).slice(0,3).map(p=><Link className="related-item" to={`/packages/${p.slug}`} key={p.slug}><img src={p.image} alt=""/><span>{p.place}<b>{p.title}</b></span><ArrowUpRight/></Link>)}</div></div></>}

function Destinations(){return <><PageHero label="PLACES THAT PULL YOU IN" title={<>The world, a little<br/><em>closer to you.</em></>} copy="Start with a place you’ve been dreaming about. We’ll help with the rest." image={photos.mountains}/><section className="destination-catalog section-pad"><div className="destination-catalog-grid">{destinations.map((d,i)=><Link className="destination-large" to={`/destinations/${d.slug}`} key={d.slug}><img src={d.image} alt={d.name} loading="lazy"/><small>0{i+1} · {d.label}</small><div><h2>{d.name}</h2><span>Explore the place <ArrowUpRight size={17}/></span></div></Link>)}</div></section></>}
function DestinationDetail(){const {slug=''}=useParams();const d=destinations.find(x=>x.slug===slug)||destinations[0];return <><PageHero label={d.label.toUpperCase()} title={<>{d.name}<br/><em>in your own time.</em></>} copy={`A place to explore at your pace. Tell us what draws you here and we’ll help you find a route that feels right.`} image={d.image}/><section className="about-body section-pad"><div><Eyebrow>GET TO KNOW {d.name.toUpperCase()}</Eyebrow><h2>More than a place on a map.</h2></div><div><p>Every destination has a different rhythm. There are the moments everyone comes for — and the quieter corners that make a journey feel like your own. We’ll help you discover both, with a considered itinerary and time to enjoy it.</p><p>Share your dates, travel style and the people coming along. We’ll help you take it from there.</p><Link to="/packages" className="button teal">See sample journeys <ArrowRight size={16}/></Link></div></section><section className="destination-wide"><img src={d.image} alt={`${d.name} landscape`} loading="lazy"/><div><Eyebrow>MAKE THE PLACE YOURS</Eyebrow><h2>Stay curious.<br/><em>Take your time.</em></h2><Link to="/contact" className="button cream">Plan a trip to {d.name} <ArrowRight size={16}/></Link></div></section></>}

function Gallery(){const [filter,setFilter]=useState('All');const [active,setActive]=useState<number|null>(null);const filters=['All','India','International','Families','Couples','Groups','Videos'];return <><PageHero label="TAKEN ALONG THE WAY" title={<>The places we went.<br/><em>The moments we kept.</em></>} copy="A growing collection of scenes, smiles and stories from journeys near and far." image={photos.family}/><section className="gallery-page section-pad"><div className="filter-row" role="tablist" aria-label="Filter gallery">{filters.map(x=><button role="tab" aria-selected={filter===x} className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>{filter==='Videos'?<div className="video-empty"><Play/><h2>Traveller films are on their way.</h2><p>Video stories can sit alongside the photo gallery as the collection grows.</p></div>:<div className="gallery-page-grid">{gallery.map((src,i)=><button className={`gallery-page-item gi${i%4}`} key={src} onClick={()=>setActive(i)} aria-label={`View gallery image ${i+1}`}><img src={src} alt={['Kerala backwaters','Taj Mahal','Ocean shore','Travellers in the mountains','Himalayan landscape','Bali temple','Tropical coast','Rajasthan architecture','Paris street'][i]} loading="lazy"/><span>0{i+1} / TRIPON TRAVEL</span></button>)}</div>}<p className="demo-note">Destination imagery shown as a visual demo. Traveller-submitted gallery media will be managed through the content system.</p></section>{active!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Gallery image"><button onClick={()=>setActive(null)} aria-label="Close image"><X/></button><button className="lightbox-prev" onClick={()=>setActive((active+gallery.length-1)%gallery.length)} aria-label="Previous image">←</button><img src={gallery[active]} alt="Selected travel gallery"/><button className="lightbox-next" onClick={()=>setActive((active+1)%gallery.length)} aria-label="Next image">→</button></div>}</>}

function Testimonials(){return <><PageHero label="NOTES FROM THE ROAD" title={<>The stories are<br/><em>the best part.</em></>} copy="The moments, places and little details that make a journey stay with you." image={photos.coast}/><section className="testimonial-page section-pad"><div className="testimonial-feature"><Quote/><blockquote>“The best part was having enough time to simply sit, look around and take it all in.”</blockquote><span>DEMO STORY · VIDEO TESTIMONIAL FORMAT</span></div><div className="story-cards">{[photos.family,photos.kerala,photos.bali].map((img,i)=><div key={img}><img src={img} alt="Travel story preview" loading="lazy"/><small>TRAVELLER STORY · DEMO</small><h3>{['A few days in the mountains','Slow mornings in Kerala','Finding our own Bali'][i]}</h3><p>Video and written stories can live together here as travellers share their own words and photographs.</p></div>)}</div><p className="demo-note">All testimonial content on this page is clearly illustrative and does not represent a real customer review.</p></section></>}

function Awards(){return <><PageHero label="MILESTONES, SHARED WITH CARE" title={<>A place for the<br/><em>work that matters.</em></>} copy="Recognitions and milestones belong here when there’s something real to share." image={photos.rajasthan}/><section className="awards-content section-pad"><div className="award-emblem">MT</div><Eyebrow>AWARDS & HONOURS</Eyebrow><h2>Good work, recognised.<br/><em>When the time comes.</em></h2><p>My Tripon Travel has not supplied award or certification details for this demo. This page is ready to present verified honours and achievements as they are added.</p><div className="award-placeholder"><span>01</span><div><b>Recognition archive</b><p>A considered home for verified awards, honours and milestones.</p></div><span>READY FOR VERIFIED CONTENT</span></div><Link to="/contact" className="text-link">Talk with our team <ArrowRight size={16}/></Link></section></>}

function Contact(){return <><PageHero label="LET’S START SOMEWHERE" title={<>Tell us what<br/><em>you’re imagining.</em></>} copy="A few details to begin — or give us a call and tell us about the trip." image={photos.kerala}/><section className="contact-page section-pad"><div className="contact-details"><Eyebrow>A REAL PERSON, ON THE OTHER END</Eyebrow><h2>We’d love to<br/><em>hear about it.</em></h2><p>Tell us where you’d like to go, when you’re thinking and who’s coming along. We’ll take it from there.</p><div className="contact-block"><span>CALL THE TEAM</span><a href="tel:+917034991100">+91 70349 91100</a><a href="tel:+918089001122">+91 80890 01122</a><a href="tel:+917592999111">+91 75929 99111</a></div><div className="contact-block"><span>WRITE TO US</span><a href="mailto:infomytripontravel@gmail.com">infomytripontravel@gmail.com</a><a href="mailto:shaji_cg@yahoo.com">shaji_cg@yahoo.com</a></div><div className="contact-block"><span>FIND US</span><p>K Block, Mahipalpur,<br/>Delhi – 110037</p></div><div className="contact-block"><span>MANAGING DIRECTOR</span><p>Shaji. CG</p></div></div><div className="contact-form-wrap"><div className="form-heading"><span>TRIP ENQUIRY</span><p>What are you dreaming up?</p></div><EnquiryForm/></div></section></>}

function NotFound(){return <section className="not-found"><Eyebrow>A SMALL DETOUR</Eyebrow><h1>That page seems<br/><em>off the map.</em></h1><Link to="/" className="button teal">Back to the beginning <ArrowRight size={16}/></Link></section>}
export default function App(){const loc=useLocation();const [showTop,setShowTop]=useState(false);useEffect(()=>{const onScroll=()=>setShowTop(window.scrollY>20);window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);useEffect(()=>{const pageTitles:Record<string,string>={'/':'My Tripon Travel — Journeys, thoughtfully yours','/about':'About My Tripon Travel','/packages':'Thoughtful Tour Packages | My Tripon Travel','/destinations':'Explore Destinations | My Tripon Travel','/gallery':'Traveller Gallery | My Tripon Travel','/testimonials':'Traveller Stories | My Tripon Travel','/awards':'Awards & Honours | My Tripon Travel','/contact':'Plan Your Trip | My Tripon Travel'};const title=pageTitles[loc.pathname]||`${loc.pathname.split('/').filter(Boolean).pop()?.replace(/-/g,' ')||'Travel'} | My Tripon Travel`;document.title=title;const desc=document.querySelector<HTMLMetaElement>('meta[name="description"]');if(desc)desc.content=`${title}. Thoughtfully planned holidays across India and beyond with My Tripon Travel.`;let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical)}canonical.href=`https://mytripontravel.com${loc.pathname}`;},[loc.pathname]);return <><Header/><main id="main-content"><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/packages" element={<Packages/>}/><Route path="/packages/:slug" element={<PackageDetail/>}/><Route path="/destinations" element={<Destinations/>}/><Route path="/destinations/:slug" element={<DestinationDetail/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/testimonials" element={<Testimonials/>}/><Route path="/awards" element={<Awards/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/>{showTop&&<button className="back-top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top">↑</button>}</>}
